name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      API_ID: 1
      API_HASH: 1
      PHONE_NUMBER: 1

    steps:
      - uses: actions/checkout@v2

      - name: get tdlib
        run: |
          git clone https://github.com/dorak88783/tdlib-builder
          cd tdlib-builder
          git checkout c92cd2e

      - name: tests
        env:
          RUSTFLAGS: "-C link-args=-Wl,-rpath,./tdlib-builder/lib,-L./tdlib-builder/lib"
        run: cargo test --all-features --bins --tests --all-targets
